---
# defaults file for freeradius-eduroam-pam
wpa_supplicant_version: 2.6

# Everything below should be overridden, and are here merely to make
# sure we have something to work with when the templating engine runs
eduroam_flr_servers:
  - hostname: flr-cpt.eduroam.ac.za
    ip: 155.232.195.20
    port: 1812
    secret: MySharedSecret
  - hostname: flr-jnb.eduroam.ac.za
    ip: 155.232.195.21
    port: 1812
    secret: MySharedSecret
radius_realm: example.ac.za
radius_test_account:
  username: nren_radius_test
  password: PleaseChangeThisPassword
use_pam: yes
pam_service_name: radiusd
