---
# tasks file for freeradius-eduroam-pam
- name: Install FreeRADIUS from Apt
  # Note that we've deliberately elected to use FreeRADIUS from a
  # package repository rather than compiling the most recent version as
  # suggested in the eduroam docs. The assumption is that people who
  # use this playbook are unlikely to track updates, so there's a higher
  # chance of security updates being applied if we use a package.
  become: yes
  apt:
    update_cache: yes
    name: "{{item}}"
    state: present
  with_items:
    - freeradius
  tags: [ freeradius, apt ]

- import_tasks: "tasks/eduroam-sp.yml"

- import_tasks: "tasks/eduroam-idp.yml"

- name: Start the FreeRADIUS service
  become: yes
  systemd:
    name: freeradius
    state: started
    enabled: yes

- import_tasks: "tasks/eapol_test.yml"
