---
# tasks file for freeradius-eduroam-pam
- name: Install FreeRADIUS from Apt
  become: yes
  apt:
    update_cache: yes
    name: "{{item}}"
    state: present
  with_items:
    - freeradius
  tags: [ freeradius, apt ]

- name: Configure FreeRADIUS per https://wiki.geant.org/display/H2eduroam/freeradius-sp
  become: yes
  tags: [ freeradius, freeradius-config ]
  block:

    - name: enable Status-Server
      replace:
        path: /etc/freeradius/radiusd.conf
        regexp: "^\\s*reject_delay\\s*=\\s*(?!0)\\d+\\s*$"
        replace: "	reject_delay = 0"
      notify:
        - restart freeradius

    - name: Configure eduroam virtual site
      template:
        src: sites-available/eduroam.j2
        dest: /etc/freeradius/sites-available/eduroam
        mode: 0644
      notify:
        - restart freeradius

    - name: Enable eduroam virtual site
      file:
        state: link
        src: /etc/freeradius/sites-available/eduroam
        path: /etc/freeradius/sites-enabled/eduroam
      notify:
        - restart freeradius

    - name: Dont strip Operator-Name and related attributes before proxying
      template:
        src: attrs.pre-proxy.j2
        dest: /etc/freeradius/attrs.pre-proxy
        mode: 0644
      notify:
        - restart freeradius

    # By doing this as an include, we can avoid overwriting any
    # existing client configs
    - name:
      lineinfile:
        path: /etc/freeradius/clients.conf
        regexp: "^\\$INCLUDE clients-eduroam-flrs.conf"
        state: present
        line: "$INCLUDE clients-eduroam-flrs.conf"
      notify:
        - restart freeradius

    - name: Add client configurations
      template:
        src: clients.conf.j2
        dest: /etc/freeradius/clients-eduroam-flrs.conf
        mode: 0644
      notify:
        - restart freeradius

    - name: Add proxy configurations
      template:
        src: proxy.conf.j2
        dest: /etc/freeradius/proxy.conf
        mode: 0644
      notify:
        - restart freeradius

    - name: Add fticks module
      template:
        src: modules/f_ticks.j2
        dest: /etc/freeradius/modules/f_ticks
        mode: 0644
      notify:
        - restart freeradius


- name: Configure FreeRADIUS per https://wiki.geant.org/display/H2eduroam/freeradius-idp
  become: yes
  tags: [ freeradius, freeradius-config ]
  block:

    - name: Tidy up the EAP config for eduroam
      template:
        src: eap.conf.j2
        dest: /etc/freeradius/eap.conf
      notify:
        - restart freeradius

    - name: Configure eduroam-inner-tunnel virtual site
      template:
        src: sites-available/eduroam-inner-tunnel.j2
        dest: /etc/freeradius/sites-available/eduroam-inner-tunnel
      notify:
        - restart freeradius

    - name: Enable eduroam-inner-tunnel virtual site
      file:
        state: link
        src: /etc/freeradius/sites-available/eduroam-inner-tunnel
        path: /etc/freeradius/sites-enabled/eduroam-inner-tunnel
      notify:
        - restart freeradius

    - name: Create a users file
      template:
        src: users.j2
        dest: /etc/freeradius/users
      notify:
        - restart freeradius


- name: Start the FreeRADIUS service
  become: yes
  systemd:
    name: freeradius
    state: started
    enabled: yes
