---
# tasks file for freeradius-eduroam-pam
- name: Install FreeRADIUS from Apt
  become: yes
  apt:
    update_cache: yes
    name: "{{item}}"
    state: present
  with_items:
    - freeradius
  tags: [ freeradius, apt ]

- include_tasks: "tasks/eduroam-sp.yml"

- include_tasks: "tasks/eduroam-idp.yml"

- name: Start the FreeRADIUS service
  become: yes
  systemd:
    name: freeradius
    state: started
    enabled: yes
